default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  encoding: unicode
  database: mihc_dev
  username: postgres
  password: 'lucho005'
  host: localhost

test:
  <<: *default
  database: mihc_test
  encoding: unicode
  username: postgres
  password: 'lucho005'
  host: localhost

production:
  <<: *default
  encoding: unicode
  database: mihc_prod
  username: postgres
  password: 'lucho005'
  host: localhost
