class ProctochologicalExamination < ApplicationRecord
  HOUR = ["NINGUNA","1", "2","3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "EN CORONA"].freeze
  ANAL_SPHINCTER_TONICITY_TYPE = ["NINGUNA","TONICO", "HIPOTONICO", "HIPERTONICO"].freeze
  RECTAL_AMPOULE_TYPE = ["LIBRE","OCUPADA"].freeze
  OCCUPIED_RECTAL_AMPOULE_TYPE = ["NINGUNA", "MF BLANDA","C/ SANGRE", "C/ MOCO", "C/PUS", "MELENA", "BOLO", "CUERPO EXTRAÑO"].freeze
  FORMATION_POSITION_OPTION = ["NINGUNA", "ANTERIOR", "POSTERIOR", "DERECHA", "IZQUIERDA", "CIRCUNFERENCIAL"].freeze
end
